sudo: required
dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install flake8
  - pip install -r requirements.txt
  - pip install .
  - pip install -e .


before_script:
  - flake8 app hseling_api_*

script:
  - pytest